@echo off
chcp 65001 >nul
setlocal EnableExtensions
title WebSurf-viewer - Start
cd /d "%~dp0"

set PORT=8101
if not "%~1"=="" set PORT=%~1

REM ---- start = 单独启动：不做任何构建，只服务已打包的 dist/ ----

if exist "%~dp0dist\index.html" goto :dist_ok
echo [ERROR] dist\index.html not found - nothing to start.
echo [HINT] Run build.cmd first, then retry.
pause
exit /b 1
:dist_ok

netstat -ano | findstr ":%PORT% " | findstr "LISTENING" >nul 2>&1
if errorlevel 1 goto :start_server
echo [WARN] Port %PORT% is already in use.
echo [WARN] Cannot verify the occupant serves this project's dist\ - not opening the browser.
echo [HINT] Use another port:  start.cmd ^<port^>
exit /b 0

:start_server
echo ============================================================
echo   WebSurf-viewer - Start (dist, no rebuild)
echo   Server:  http://localhost:%PORT%/
echo   App:     http://localhost:%PORT%/index.html
echo   Close this window to stop the server.
echo ============================================================

REM 起服务三级回退：产物自带启动器 -> python -> npx serve；守卫**不得**遮蔽更优路径。
if exist "%~dp0dist\play.cmd" (
  REM That launcher (generated by apps/viewer/scripts/build-dist.mjs) serves dist\ and opens the page.
  call "%~dp0dist\play.cmd" %PORT%
  exit /b 0
)
where python >nul 2>nul
if not errorlevel 1 (
  REM A detached "cmd /c" opens the page after timeout /t 1; the server call below blocks.
  start "" /min cmd /c "timeout /t 1 /nobreak >nul & start "" http://localhost:%PORT%/index.html"
  REM src/serve.py takes its serve root from argv[2]; here it is dist\ itself.
  python "%~dp0..\..\src\serve.py" %PORT% "%~dp0dist"
  exit /b %errorlevel%
)
where npx >nul 2>nul
if not errorlevel 1 (
  echo [WARN] python not found - using Node fallback: npx serve ^(no COOP/COEP; SAB path degrades^).
  start "" /min cmd /c "timeout /t 1 /nobreak >nul & start "" http://localhost:%PORT%/index.html"
  npx --yes serve -l %PORT% "%~dp0dist"
  exit /b %errorlevel%
)
echo [ERROR] Neither dist\play.cmd nor Python 3 nor Node/npx is available.
echo [HINT] Run build.cmd first (it generates dist\play.cmd), or install Python 3 / Node.js.
pause
exit /b 1
